- name: checking data types
  hosts: localhost
  vars:
    name: sivakumar
    Skills: # It is list type
    - DevOPs
    - shell
    - ansible
    - Linux
    Experience: # It is a Map type, bcoz it contain key-value pairs
      DevOPs: 7
      AWS: 6
      Docker: 4
    trainer: true #boolean
  tasks:
  - name: print key-value pair
    ansible.builtin.debug:
      msg:"name: {{name}}"

  - name: print list
    ansible.builtin.debug:
    msg: "skills: {{skills}}"

  - name: print list
    ansible.builtin.debug:
    msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
    msg: "trainer: {{trainer}}"

 
