- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install/uninstall packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
      #state: present
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'nginx', state: 'present'}
    - {name: 'postfix', state: 'absent'}
    